### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Sencc** [BooHwang/segment_anything_tensorrt#4]
hi, this project is great, but I have some problems. I want to convert the sam_default_prompt_mask_.onnx model to tensorrt, but there is an error: [graph.cpp::symbolicExecute::539] Error Code 4: Internal Error (/OneHot: an IIOneHotLayer cannot be used to compute a shape tensor)
I followed your tutorial completely. I also tried to set different values for opset_version, but it didn’t work.How can I solve it, looking forward to your answer.
tensorrt version:8.6.1
opset_version:15-17
onnxsim: Ture

**Comment by summelon** [comment]
Hi, could you share how did you solve it?
I encountered the exact same error.
